/**
* This file is part of "balise_codec".
* balise_codec is free software: you can distribute it and/or modify it under the terms of the GNU Lesser General Public License as
* published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
* This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
* See the GNU Lesser General Public License for more details.
* You should have received a copy of the GNU General Public License along with this program.
* If not, see < https://www.gnu.org/licenses/>.
*/

#include "lookup_tables.h"

t_word transform_word10_to_word11(unsigned int val10)
// converts the 10-bit input to the 11-bit output
// performs a range check, stops the program if val10 is out of range
{
    if (val10 > N_TRANS_WORDS-1)
    // overflow, stop the program
    {
        printf("Overflow error in transform_word10_to_word11 (val10=%d), quitting.\n", val10);
        exit(ERR_LOGICAL_ERROR);
    }

    return (t_word)(transformation_words[val10]);
}

t_word transform_word11_to_word10(unsigned int val11)
// returns the index of val11 in the transformation words (returning its index, which is a val10).
// returns NO_TW (-1) if it does not exist.
// uses a lookup table that was generated from the transformation words, to save some clock ticks.
// performs a range check, stops the program if val10 is out of range
{
    if (val11 > N_TW_INVERTED - 1)
    // overflow, stop the program
    {
        printf("Overflow error in transform11to10 (val11=%d), quitting.\n", val11);
        exit(ERR_LOGICAL_ERROR);
    }

    return (t_word)transformation_words_inverted[val11];
}



/*
// Scramble-lookup table was generated with this code:

void fill_lookup_table(void)
{
    unsigned int i, scrambled, output_bit, lfsr;
    int j, t;

    for (i = 0; i < TABLE_SIZE; i++)
    {
        lfsr = 0;
        scrambled = 0;
        for (j = 9; j >= 0; j--)
        {
            t = lfsr >> 31;
            output_bit = ((i >> j) & 1) ^ t;
            lfsr <<= 1;
            if (output_bit)
            {
                lfsr ^= H;
                scrambled += (1 << j);
            }
        }

        lookup_table[i].reg = lfsr;
        lookup_table[i].out = scrambled;
        lookup_table[scrambled].reverse = i;
    }

    for (i = 0; i < TABLE_SIZE; i++)
    {
        printf("{0x%08x, 0x%03x, 0x%03x},", lookup_table[i].reg, lookup_table[i].out, lookup_table[i].reverse);
        if ((i + 1) % 8 == 0)
            printf("\n");
    }

}

*/


// Checkbits-lookup tables were generated with this code (AI generated by Claude and Gemini):

/* ───────────────────────────────────────────────────────────────────
 * 2.  Table construction
 * ───────────────────────────────────────────────────────────────────
 *
 * For each possible byte value b (0..255) the table stores the 85-bit
 * remainder that results from feeding b into the top 8 positions of
 * the shift register and clocking 8 times.
 *
 * Shift-register rule (standard CRC / GF(2) long division):
 *   1. If the MSB of the register (bit 84) is 1, XOR with the
 *      "feedback polynomial" p, which is f·g with the leading term
 *      (x^85) removed.
 *   2. Shift the register left by 1.
 *
 * Repeating this 8 times for the 8 bits of b gives one table entry.
 */
/*
static void build_table(t_crc_entry table[256],
    uint32_t fg0, uint32_t fg1, uint32_t fg2)
{
    const uint32_t p0 = fg0;
    const uint32_t p1 = fg1;
    const uint32_t p2 = fg2 ^ (1u << 21);

    for (int b = 0; b < 256; b++)
    {
        uint32_t r0 = 0;
        uint32_t r1 = 0;
        uint32_t r2 = (uint32_t)b << 13;

        for (int bit = 0; bit < 8; bit++)
        {
            const bool msb = (r2 >> 20) & 1u;

            r2 = (r2 << 1) | (r1 >> 31);
            r1 = (r1 << 1) | (r0 >> 31);
            r0 = (r0 << 1);
            r2 &= 0x001FFFFFu;

            if (msb)
            {
                r0 ^= p0;
                r1 ^= p1;
                r2 ^= p2;
            }
        }

        table[b] = { r0, r1, r2 };
    }
}

/// Call this once at programme start-up.
void crc_table_init()
{
    // f·g polynomials from Subset-036 (same constants as in compute_check_bits):
    build_table(crc_table_long,
        0xC063B091u, 0x890C6F72u, 0x003EC171u);
    build_table(crc_table_short,
        0x021B6D65u, 0x87757959u, 0x002BB94Du);
  
    // print the tables to be included as constants in the tool:
    for (int i = 0; i < 256; i++)
    {
        printf("{0x%08x, 0x%08x, 0x%08x}, ", crc_table_short[i].w[0], crc_table_short[i].w[1], crc_table_short[i].w[2]);
        if ((i+1) % 4 == 0)
            printf("\n");
    }
    
    crc_tables_ready = true;
}
*/